User's Guide
------------

This part of the documentation answers most of the questions about how to
use the Railgun system.

.. toctree::
   :maxdepth: 2

   userguide/foreword
   userguide/installation
   userguide/configuration
   userguide/homework
   userguide/practice

.. _design:

System Design
-------------

If you want to make some development on Railgun, you may get started with
this documentation on :ref:`design_overview`.

.. toctree::
   :maxdepth: 2

   design/overview
   design/multilang
   design/webapi

.. _api:

API Reference
-------------

If you are looking for information on a specific function, class or method,
this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api/common
   api/website
   api/runner
   api/runlib
