User's Guide
------------

This part of the documentation answers most of the questions about how to
use the Railgun system.

.. toctree::
   :maxdepth: 2

   userguide/foreword
   userguide/installation
   userguide/homework
   userguide/practice

Framework
---------

If you want to make some development on Railgun, you may get started with
this documentation on system design.

.. toctree::
   :maxdepth: 2

   framework

API Reference
-------------

If you are looking for information on a specific function, class or method,
this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api
